### ISSUE TITLE
Voice keyboard crashes iVim

### ISSUE THREAD

**Issue by drbarrett** [terrychou/iVim#28]
Hitting the dictation button on the soft keyboard causes iVim to crash. Once the dictation keyboard appears pressing either the keyboard or mute icons triggers the crash.

Turning off dictation in the settings app works around the problem.

**Comment by terrychou** [comment]
Fixed this problem and added support for dictation input.
Also, I have added your email address into the TestFlight list so that you can test it on the device. Let me know if you prefer other ways.

**Comment by drbarrett** [comment]
I downloaded the testflight build, but it looks like it’s a few weeks old.

I’ll build it here and try it out when I get a chance if there isn’t an updated testflight build with it.

**Comment by drbarrett** [comment]
I just downloaded 1.30 and it opens and closes the dictation keyboard correctly. I switched in and out of it a couple dozen times and couldn't get it to break. 

But if I try to dictate anything it still crashes.

This is on an iPad pro with IOS 11.2

**Comment by terrychou** [comment]
I have pushed up a branch named "dictation". You can build and run it to get more helpful information about the crash. The TestFlight is not so helpful with debugging, honestly.

By the way, I am not having crashes on the dictation input so far.

**Comment by drbarrett** [comment]
I'll test it, but I'm not actually interested in dictation personally. My problem was mainly in hitting the dictation button by mistake and you fixed that. So don't invest much energy in this unless you feel it's useful.

**Comment by terrychou** [comment]
It turned out caused by the difference of compiling optimizing.
I'll submit another build to TestFlight.
It is not about "being useful" or not. To me, it is a problem led by the fixed one. It is not guaranteed that no users would touch this bug after the first one is fixed. So if I release it while leaving the problem there, it would happen for other users. It is not good. :)

**Comment by drbarrett** [comment]
It’s working for me now. And I agree, I just wasn’t sure how high a priority it was. Kinda neat to be able to do voice input to vim anyway.
